name: Run Fetch Articles Script

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Firebase credentials file
        run: |
          mkdir -p config
          printf '%s' "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" | base64 -d > config/firebase.json

      - name: Run fetch script
        run: python fetch_articles.py

      - name: Finish
        run: echo "✅ Done"
