name: Run Fetch Articles Script

on:
  schedule:
    - cron: '0 8 * * *'  # Everyday at 8h UTC
  workflow_dispatch:    # Manual launch from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository clone
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies installation
        run: pip install -r requirements.txt

      - name: Execute Python script
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: |
          mkdir -p config
          echo "$FIREBASE_CREDENTIALS_JSON" > config/pathmaster-327b2-firebase-adminsdk-fbsvc-708e63f7c0.json
          python fetch_articles.py

      - name: Finish
        run: echo "Script executed !"
